import { Aref_Ruqaa } from "next/font/google";
import "./globals.css";
import Header from "./../components/Header";
import Footer from "./../components/Footer";

const arefRuqaa = Aref_Ruqaa({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={arefRuqaa.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
